alias ll='ls -l'
alias lrt='ls -lrt'
alias lla='ls -la'
alias cd..='cd ..'
alias cd...='cd ../..'
alias -- ++='pushd +0'
alias -- --='pushd -1'
alias mmv='noglob zmv -W'
alias rm='rm -v'
alias mv='mv -v'
alias cp='cp -v'
alias tmux='TERM=xterm-256color /usr/bin/tmux'
